version: "3.6"

services:
  docere_api:
    build:
      context: .
    command: ["npx", "nodemon", "build"]
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ../docere-config:/app/node_modules/docere-config
    working_dir: /app
