version: "3.6"

services:
  api:
    build:
      context: .
    command: ["npx", "nodemon", "build"]
    # command: ["node", "build"]
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ../docere:/app/node_modules/docere
      - ../docere/node_modules/react:/app/node_modules/react
      - ../docere-projects:/app/node_modules/docere-projects
    working_dir: /app
